project:
  type: website
  output-dir: docs
  
website:
  title: "Curriculum Vitae"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - CurrentProjects.qmd
      - Publications.qmd
      - Presentations.qmd
     
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    mainfont: "mmonospace"



