---
title: "About Me"
---

Dr. Jemel P. Aguilar is an associate professor at Fordham University [Graduate School of Social Services](https://www.fordham.edu/graduate-school-of-social-service/) . He specializes in human behavior in the social environment with an emphasis on theory development and testing. Human behavior in the social environment is a vast area of study so Dr. Aguilar employs qualitative, quantitative, and computational approaches to answer his research questions. As a clinician, he practices with low-income and uninsured children and families that experienced traumatic situations, marginalized chronic illnesses, or clinicians interested in serving these populations. He is independently licensed in the State of Connecticut. Dr. Aguilar earned his PhD in Social Welfare and Master of Social Work from the University of Minnesota, and a Master of Public Health from Southern Connecticut State University.

## Current academic position

Associate Professor at Graduate School of Social Services at Fordham University

## Education

*PhD in Social Work & Master of Social Work*\
University of Minnesota Twin Cities Minneapolis, Minnesota

*Master of Public Health*\
Southern Connecticut State University New Haven, Connecticut

*Bachelor of Human Development*\
Empire State College, New York, New York

## Certifications

*Child Abuse Prevention Studies Certificate – Level I*\
University of Minnesota Twin Cities Minneapolis, Minnesota

*Child Abuse Prevention Studies Certificate – Level II*\
University of Minnesota Twin Cities Minneapolis, Minnesota
