---
title: "Current Projects"
format: html
---

## **Qualitative Studies** 

***Exploring the Structure and Components of Oppression***

Principal Investigator: Jemel P. Aguilar 

Concept analysis is a social scientific process in which researchers dissect concepts into their constituent parts, to explore the meaning and typical nature of the concept (see Wilson, 1963).  Oppression is a poorly defined concept needing analysis to identify its typical nature, meaning, and constituent parts(Cudd, 2016; Dong & Temple, 2011; Dotson, 2014). In this study, we analyze oppression using concept analysis to: (1) identify its nature, meaning, and constituent parts, (2) explain the social relations in descriptions of oppression, and (3) formulate a conceptual definition and theoretical model of oppression. The results of this endeavor will shape future studies on the relationship between oppression and disparities in chronic diseases as well as developing instruments about oppression. 

Contact Dr. Aguilar to participate  <jaguilar35@gmail.com>

## **Mixed Methods Studies**

***Woke Games: A quantitative ethnographic study of oppression in the video game industry***

Principal Investigator: Jemel P. Aguilar

When developers include diversity in games, anti-woke gamers take to discussion forums and YouTube to identify and review bomb these games. Anti-woke gamers mirror the objections to wokeness in American society, but the patterns in gamer discourse have yet to be examined. Therefore, I seek funding to explore the discourse about “wokeness” in video games and answer the questions: What are the anti-woke discourse patterns among gamers? How do these patterns indicate facets of gamer’s cultural norms and values? How, if at all, are these digital protests and calls to avoid games affecting sales or player counts? How might this response to diversity in video games be an expression of societal oppression? This study builds upon my prior research findings about definitions of oppression in American society by examining a social segment advocating for exclusion and oppression. 



