---
title: "Presentations"
format: html
---

## PROFESSIONAL CONFERENCES

### International and National

Sultana, S. & **Aguilar, J.P.** (2025). Examining correlates of Mental Health Among Bangladeshi Street Children: A cross-sectional Study. Poster Presented at Presented at the 71th Annual Meeting of the Council on Social Work Education 

Iacono, G., Holle, L., **Aguilar, J.P.**, Switz, M., Smith, J. S. (2022). Unpacking Neutrality in Social Work Education: Exploring Twitter Responses to Anti-Trans Legislation. Presented at Leading Critical Conversations: Human Rights are Global Rights.  

**Aguilar, J.P.**, Sultana, S., & Marlowe, D. (2023). Acting up: Dedicated, anti-oppression mentorship between faculty with marginalized identities. Council on Social Work Education 69th Annual Program Meeting - It's Time to Act: Defining and Reckoning with Anti-Racist Social Work Education

**Aguilar, J.P.** & Counselman-Carpenter, E. (2002). Decolonizing Human Behavior in the Social Environment: Restructuring Knowledge and Dynamic Teaching Strategies. Teaching Institute presented at Council on Social Work Education 68th Annual Program Meeting Leading Critical Conversations: Human Rights are Global Rights.  

Sultana, S. & **Aguilar, J.P.** (2022). Does Disclosure, social support, and religiosity lead to HIV stigma? examining Bangladeshi poor women's experience with HIV? Society for Social Work and Research 27th Annual Conference - Social Work Science and Complex Problems: Battling Inequities + Building Solutions

Sultana, S. & **Aguilar, J.P.** (2022). More than just a friend:" Shielding from stigma through social support - An examination of Poor Bangladeshi Women Living with HIV. Presented at the 13th Annual International Conference on Stigma Power of Peer Support – Breaking the Chains of Stigma Together. 

Counselman-Carpenter, E. & **Aguilar, J.P.** (2021). Strengthening Online Teaching Pedagogy. Presented at the 14th Annual Learning Ideas Conference: Innovations in Learning and Technology for the Workplace and Higher Education. 

Counselman-Carpenter, E. & **Aguilar, J.P.** (2021). Understanding the intersections of faculty literacy, institutional support, & Perspectives on Digital Immigrations: Impacts on Curricular and Student Development. Presented at 25th Annual Conference & Anniversary Celebration of the Society for Social Work and Research

**Aguilar, J.P.**, Tomczak, S. M., & Wade-Rancourt, R. (2018). Poverty simulations in social work education for policy practice.  Presented at the 65th Annual Meeting of the Council on Social Work Education

**Aguilar, J.P.** (2015). HIV knowledge, risk behavior, stigma, and their impact on HIV testing among Asian American and Pacific Islanders. Presented at the 61th Annual Meeting of the Council on Social Work Education

Sultana, S. & **Aguilar, J.P.** (2015). HIV/AIDS, Women, Stigma: A Changing Global Perspective. Presented at the 61th Annual Meeting of the Council on Social Work Education.

**Aguilar, J.P.**, Jung, H., & Morris, M. (2013). Policy facilitated health disparities. Presented at the 5th Annual Health Disparities Conference at Teachers College, Columbia University 

**Aguilar, J.P.** (2011). Heterosexisms in the Profession: Is social work profession ready to take on the paradoxes and pitfalls of the implicit curriculum? Presented at the 57th Annual Meeting of the Council on Social Work Education

Lagana-Riordan, C. & **Aguilar, J.P.** (2008). What's Missing from NCLB? A Policy Analysis from a Social Work Perspective. Presented at the 54th Annual Meeting of the Council on Social Work Education

**Aguilar, J.P.** & Lagana-Riordan, C. (2008). Fueling changes in school social work practice. Presented at the 54th Annual Meeting of the Council on Social Work Education

**Aguilar, J.P.** (2008). The power of female drug dealers. 2008 Presented at the Annual meeting of the Society for the Study of Social Problems.

**Aguilar, J.P.** & Berger-Cardosa, J. (2008). Immigration policy and its impact on the family. Presented at the 2008 Annual meeting of the Society for the Study of Social Problems.

Armour, M. & **Aguilar, J.P.** (2007). “Using Context to Build Methodological Rigor: Application to a Study of Change Processes in a Restorative Justice Intervention.” Presented at the 4rd Annual International Congress on Qualitative Inquiry. Champaign-Urbana Illinois.

**Aguilar, J.P.**, Armour, M. & Balliro, M. (2007). Assessing Context for Building Methodological Rigor in Research: Application to the Study of Change Processes in a 12-Week In-Prison Restorative Justice Group Intervention. Presented at the 4rd Annual International Congress on Qualitative Inquiry. Champaign-Urbana Illinois.

**Aguilar, J.P.** (2007). Certificates of Confidentiality in research on youth at risk. Presented at the 3rd Annual International Congress on Qualitative Inquiry. Champaign-Urbana Illinois

**Aguilar, J.P.** & Lagana-Riordan, K. (2007). “Providing insight into accountability using a concept analytic process.” Presented at the 3rd Annual International Congress on Qualitative Inquiry. Champaign-Urbana Illinois.

**Aguilar, J.P.** (2006). “Criminalizing color: Schema theory and disproportionate minority confinement in America: Presented at the Society for the Study of Social Problems, Montreal Canada. 

**Aguilar, J.P.**, Abrams, L. S., Shannon, S. K. (2005). “Rethinking risk: Subjectivities and meaning in risk and resiliency.” Presented at the Society for the Study of Social Problems. Philadelphia Pennsylvania.

**Aguilar, J.P.**, Abrams, L. S., Shannon, S. K. (2005). “Rethinking risk: Subjectivities and meaning in risk and resiliency.” Presented at the First International Resilience Research Project Conference. Halifax, Nova Scotia Canada 

Abrams, L. S., **Aguilar, J.P.**, & Anderson-Nathe, B. (2004). “Juvenile corrections and adolescent masculinities.” Presented at the Society for the Study of Social Problems, San Francisco, CA.

**Aguilar, J.P.**, & Abrams, L. S. (2004). “Possible selves and behavior change trends among juvenile offenders in residential treatment.” Presented at the Annual meeting of the Society for the Study of Social Problems. San Francisco California 

**Aguilar, J.P.**, & Abrams, L. S. (2003). “Negative trends, possible selves, and behavior change: A qualitative study of juvenile offenders in residential treatment” Presented at the Annual meeting of the Society for Social Work and Research. New Orleans Louisiana

## Regional and State

### Invited

**Aguilar, J.P.** (2021). Decolonizing social work. Presented at the Rutgers University School of Social Work Adjunct Faculty Development Program. 

**Aguilar, J.P.** (2020). Community-Based Participatory Research and the development of the Energy Envelope. Presented at the 2020 Massachusetts Myalgic Encephalomyelitis/Chronic Fatigue Syndrome Research Group. 

### Non-invited

**Aguilar, J.P.**, Morris, M., & Jung, H. (2013). Under-served populations and the construction of health disparities Presented at the 2013 Healthcare Symposium University of Texas McCombs School of Business

Gupta, S.V., **Aguilar, J.P.**, Alexander, J. (2012). The lives of Blacks in Texas, 1950-2010. Presented at Nerd Night.  

**Aguilar, J.P.** (2009-2010). HIV Services in the Austin Transitional Grant Area – Lecture Series. Presented to the Austin Transitional Grant area HIV Planning Council.

**Aguilar, J.P.** (2009). Social Work Informatics: The integration of technology into human services. Presented at the Annual Meeting of the National Association of Social Workers – Texas Chapter. 

**Aguilar, J.P.** (2007). Accountability in school social work. Presented at the 13th Annual meeting of the University of Texas School of Social Work School Social Worker’s Conference

**Aguilar, J.P.** (2002). “Engaging Youth: Representing Youth in Foster Care” Presented at the Children’s Law Center of Minnesota’s Pro Bono Opportunity: Minneapolis Minnesota 

**Aguilar, J.P.** (2001). “Going Back to School: Providing Psychotherapeutic Services in School Settings.” Minnesota Association of Community Mental Health Programs Conference. Red Lake Minnesota 

**Aguilar, J.P.** (1999). “HIV prevention with youth and culturally diverse populations” presented at the University of Wisconsin at Madison’s Summit on HIV prevention with vulnerable populations. Madison Wisconsin
