---
title: "Publications"
format: html
---

## Books in Development:

**Aguilar, J. P.** Theory and theory development in Social Work and other helping professions.

**Aguilar, J. P.** Human Behavior In the Social Environment: An integrated approach that bridges theory, practice, and research.

## **Books:**

**Aguilar, J. P.** & Counselman-Carpenter, E. (2023). Multidimensional Human Behavior in the Complex Social Environment. Cognella Publishing

**Aguilar, J. P.** (2022). The practice of human behavior in the social environment. Kendall Publishing.

**Aguilar, J. P.** (2022). Social Work Research. Kendall Publishing

**Aguilar, J. P.** & Counselman-Carpenter, E. (2021). Decolonizing Human Behavior in the Social Environment: A Reader for an Anti-oppressive Approach. Cognella Publishing.

## **Peer Reviewed Journal Articles:**

Sultana, S., Wade, C. H., **Aguilar, J. P.** (2025). Stigmatized HIV Over Knowledge and Support: A quantitative study to develop and measure Bangladeshi Women’s Social Support When Living With HIV-Related Stigma. *Journal of the Association of Nurses in AIDS Care* [Preprint](https://journals.lww.com/janac/abstract/9900/stigmatized_hiv_over_knowledge_and_support__a.139.aspx)

Martin A, Celentano J, Olezeski C, Halloran J, Penque B, **Aguilar, J. P.**, Amsalem D. Collaborating with transgender youth to train healthcare professionals: randomized controlled trial of a didactic enhanced by brief videos. BMC Public Health (submitted; preprint: https://doi.org/10.21203/rs.3.rs-1588004/v1

Smith, C. F., **Aguilar, J. P.**, Kozu, S., D’Angelo, K., Keenan, E., Tomczak, S. M. If anti-racism is the goal, then anti-oppression is how we get there. Advances in Social Work, 22(2), 758-778 DOI: 10.18060/24646

Smith, C. F., **Aguilar, J. P.**, Tomczak, S. M.\* (2022). Appropriate uncomfortable: A conversation among three colleagues about structural oppression focused on racism and the need for action. Reflections: Narratives of Professional Helping, 27(2), 78-86 \*Each author contributed as first authors of this project

**Aguilar, J. P.** & Counselman-Carpenter, E. (2021). ‘The mirage of action’: Exploring the social work professions’ perpetuation of white supremacy through ‘well-intentioned’ actions. Advances in Social Work, 21(2/3), 1020-1044.

Sen, S., Petty, M., & **Aguilar, J. P.** (2020). An ecological framework for understanding HIV- and AIDS-related stigma among Asian American and Pacific Islander Men who have sex with men living in the USA. Culture, Health, & Sexuality, 23(1), 85-97.

Sen, S., Nguyen, H. D., Kim, S. Y., & **Aguilar, J. P.** (2017). HIV knowledge, risk behavior, stigma, and their impact on HIV testing among Asian American and Pacific Islanders: A review of the literature. Social Work in Public Health, 32(1), 11-29.

Jung, H. J. & **Aguilar, J. P.** (2016). Mental health is everybody’s responsibility: A case study of collaborative partnerships and shared commitment for mental health promotion. Social Work in Mental Health, 14(5), 474-496.

**Aguilar, J. P.**, Mahapatra, N., Busch-Armendariz, N.B., & DiNitto, D.M. (2016). Exploring the science of conducting surveys for studying men's sexual assault perpetration behaviors. Journal of Aggression, Maltreatment, & Trauma, 25(1), 88-109.

Sen, S., **Aguilar, J. P.**, Heng, L., & Gambhir, S. (2013). The social construct of sex work in India. Journal of HIV & Social Services, 13(4), 353-370.

**Aguilar, J. P.**, & Sen, S. (2013). The culture of methamphetamine: Exploring the socio-cultural aspects of gay and bisexual men’s use of methamphetamine. Journal of Human Behavior in the Social Environment, 23(3), 370-382.

Lagana-Riordan, C., **Aguilar, J. P.**, Franklin, C., Streeter, C., Kim, J., Tripodi, S., & Hopson, L. M. (2011). At-risk students' perceptions of traditional schools and a solution-focused public alternative school. Preventing School Failure, 55(3), 105-114.

Bender, K., Tripodi, S., **Aguilar, J. P.**, & Thompson, S. (2010). Relationship between internal and external sources of control in a national sample of young adults. Social Work Research, 34(1), 58-64

Sen, S. & **Aguilar, J. P.**, & Bacchus, D. N. A. (2010). Migration, poverty, and risk of HIV infection : An application of social capital theory. Journal of Human Behavior in the Social Environment, 20(7), 897-908.

Sen, S. & **Aguilar, J. P.** & Goldbach, J. (2010). Does social capital act as a buffer against HIV risk among migrant men in Sub-Saharan Africa? Journal of HIV/AIDS in Social Services, 9,190-211.

**Aguilar, J. P.** & Jackson, A. (2009). From the streets to institutions: Female adolescent drug seller’s perceptions of their power. Affilia, 24, 369-381.

**Aguilar, J. P.** & Sen, S. (2009). Comparing conceptualizations of social capital. Journal of Community Practice, 17(4), 424-443.

Lagana-Riordan, C. & **Aguilar, J. P.** (2009). What's Missing from NCLB? A Policy Analysis from a Social Work Perspective. Children and Schools, 31, 3, 135-146.

Armour, M., Winsor, L. & **Aguilar, J. P.**, Taub, C. (2008). A multidimensional evaluation of a faith based restorative justice intervention for offenders: A pilot study. Journal of Christianity and Psychology, 27, 159-167.

Abrams, L.S., Anderson-Nathe, B., & **Aguilar, J. P.**, (2007). Constructing adolescent masculinities and juvenile violence. Men and Masculinities, 11, 22-41.

Abrams, L.S. & **Aguilar, J. P.**. (2005). Negative trends, possible selves, and behavior change: A qualitative study of juvenile offenders in residential treatment. Qualitative Social Work, 4, 175-196.

## **Book Chapters:**

Sultana, S., & **Aguilar, J. P.** (2024). Poverty, mental health and organizational intervention for street children: Bangladesh perspective. In N. P. Rygaard, U. P. Gielen, E. P. Congress, & J. Larock (Eds.), *Children around the world: The future of our Earth* (pp. 149–158). Information Age Publishing, Inc.

Counselman-Carpenter, E. & **Aguilar, J. P.** (2022) Best practices for assessing digital literacy and strengthening online teaching pedagogy of digitally immigrant stakeholders in higher education. In David Guralnick, Michael E. Auer, & Antonella Poce. (Ed.) Innovations in Learning and Technology for the Workplace and Higher Education. New York, NY: Springer

**Aguilar, J. P.** (2020). When my body betrayed me: Falling through my identity and into Myalgic Encephalomyelitis/Chronic Fatigue Syndrome. In E. Counselman-Carpenter, E. & Redclay, A. (Ed.) Working with Grief and Traumatic Loss: Theory, Practice, and Self-Care. San Diego, CA: Cognella Publishing.

Sen, S. & **Aguilar, J. P.** (2016) Migration and HIV among Asian Populations: Social work interventions. In X. Qingwen, & L. P. Jordan (Eds), Migrant Workers: Social identity, occupational challenges and health practices (pp 66-75). Hauppauge, NY: Nova Science Publishers.

**Aguilar, J. P.** (2013). Drug sellers and distributors. In R. J. R. Levesque (Ed.). Encyclopedia of Adolescence. New York, NY: Springer

**Aguilar, J. P.** (2010). Developmental trajectories in adolescent offending. In A. Roberts and D. Springer (Eds.). Juvenile Delinquency and Juvenile Justice: Policies, Programs, and Intervention Strategies. Boston, MA: Jones & Bartlett Publishers.

**Aguilar, J. P.** (2009). Adolescent drug sellers and distributors. In A. Browne (Ed.) Comprehensive Series in Addictions. Westport, CT: Praeger-Greenwood

**Aguilar, J. P.**, & Springer, D. W. (2008). Assessment, classification, and treatment with juvenile offenders. In A. R. Roberts (Ed.), Correctional counseling and treatment (pp. 25-40). Saddle River, NJ: Prentice-Hall.

## Peer-Reviewed Articles In development:

Sultana, S. & **Aguilar, J. P.** This lonely place so far from home: Examining college students’ loneliness. Manuscript to be submitted to the *Journal of American College Health*.

**Aguilar, J. P.** The science of oppression: Where are we going and what do we know? Manuscript to be submitted to the *American Journal of Community Psychology*.

**Aguilar, J. P.**, Tomczak, S. M., Wade-Rancourt, R. Challenging social work students’ attitudes toward the poor and low-income populations through poverty simulation. Manuscript submitted to *Community Practice*

## Policy Briefs:

**Aguilar, J. P.** (2013). *State of neglect: HIV disparities in the State of Texas.* Institute for Urban Policy Research & Analysis, College of Liberal Arts, University of Texas at Austin

Gupta, S.V., Alexander, J., & **Aguilar, J. P.**, (2012). The lives of Blacks in Texas, 1950-2010. Institute for Urban Policy Research & Analysis, College of Liberal Arts, University of Texas at Austin

**Aguilar, J. P.** (2012). *HIV in State Prisons: A call for provider-initiated testing.* Institute for Urban Policy Research & Analysis, College of Liberal Arts, University of Texas at Austin.

## Research Monographs and Final Reports:

**Aguilar, J. P.** (2010). Comprehensive medical and social service needs of people living with HIV or AIDS in a 5-county area of Texas. Report to the Austin TGA HIV Planning Council

**Aguilar, J. P.** & Travis, D.J. (2007). *Review of the CAL Curriculum*. Report to the University of Texas School of Social Work Community and Administrative Leadership Committee.

Abrams, L. S., & **Aguilar, J. P.** (2004). *Anoka Bar-None Final Research Report*. Technical report prepared for the Volunteers of American Bar-None program, Anoka, MN.
