---
title: "Woke Games and Anti-Woke Culture"
author: Dr. Jemel P. Aguilar
format: 
    revealjs:
        theme: moon
        footer: "Fordham University Graduate School of Social Services"
---

# Culture Wars 
 
 - Democrats vs. Republicans
 - Liberal vs. Conservatives
 - Left vs. Right


# Digital Culture Wars

 - Gamers vs. Gamers
 - Developers vs. Gamers
 - Developers vs. Developers


# Are games woke? 

 - Mechanics
 - Content 
 - Design
 - Developers

# Steam Conversations 

 - Platform of gaming and community building
 - Community pages and discussions 
 - Groups discuss video games including the wokeness

# Data Collection 
 - Collected (Scraped) comments from one group 
 - All topics with more than 10 comments were included in the dataset
 - Dataset includes comments, date of post, author, replies, forum, hyperlinks, emojis.
 - Over 400 comments included in the dataset. 

# Data Cleaning and Preparation
 - Moving hyperlinks and emojis to separate column
 - Topic modeling for keywords relevant to the study 
 - Analysis of words to identify most frequent words


# Forums 